# Generated by Django 6.0 on 2025-12-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название компании')),
                ('company_logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Логотип компании')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория профессии')),
                ('hh_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии на HH')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на вакансию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
